name: Precompiled binaries version request
description: Use this template to automatically trigger binaries compilation for a specific Minecraft version.
title: "[Version request]"
labels: ["version request"]

body:
- type: dropdown
  id: version
  attributes:
    label: Minecraft version
    description: Which version of Minecraft do you want binaries for?
    options:
      - "1.12.2"
      - "1.13"
      - "1.13.1"
      - "1.13.2"
      - "1.14"
      - "1.14.1"
      - "1.14.2"
      - "1.14.3"
      - "1.14.4"
      - "1.15"
      - "1.15.1"
      - "1.15.2"
      - "1.16"
      - "1.16.1"
      - "1.16.2"
      - "1.16.3"
      - "1.16.4"
      - "1.16.5"
      - "1.17"
      - "1.17.1"
      - "1.18"
      - "1.18.1"
      - "1.18.2"
      - "1.19"
      - "1.19.1"
      - "1.19.2"
      - "1.19.3"
      - "1.19.4"
      - "1.20"
      - "1.20.1"
      - "1.20.2"
      - "1.20.3"
      - "1.20.4"
      - "1.20.5"
      - "1.20.6"
      - "1.21"
      - "1.21.1"
      - "1.21.2"
      - "1.21.3"
      - "1.21.4"
      - "1.21.5"
      - "1.21.6"
      - "1.21.7"
      - "1.21.8"
      - "1.21.9"
  validations:
    required: true
